name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1.2.0

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install PyGithub
        
    - name: Run platformIO
      run: platformio run

    # check if version in code is greator than version in JSON response, then deploy.
    - name: Upload .bin file and modify json file
      run: python ./.github/scripts/check_ver_and_deploy.py
